version: "4.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src        # monte ton code dans le conteneur
    environment:
      DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/monitoring_database?sslmode=disable
    command: go run ./src/cmd/server/main.go

# Pour lancement : docker-compose up --build
# Pour arrÃªt : docker-compose down | ctrl+C