# docker-compose.prod.yml 
# Version du fichier docker-compose pour la production
# Utilise ton Dockerfile pour construire l'image de l'application
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile   # ton Dockerfile qui compile ton binaire
    ports:
      - "8080:8080"
    env_file:
      - .env

# Pour lancement : docker-compose -f docker-compose.prod.yml up --build
# Pour arrÃªt : docker-compose -f docker-compose.prod.yml down | ctrl+C